### ISSUE TITLE
Feature Request: Bed preheat

### ISSUE THREAD

**Issue by olehs** [marian42/octoprint-preheat#1]
Please add a heated bed preheat (commands M140, M190)

**Comment by olehs** [comment]
Thanks again. And one more thing...
What about bed cooldown ?

**Comment by mark-hahn** [comment]
I haven't tried this yet so I don't know how it works, but I personally would like the bed to just always preheat/cool when the nozzle does.

**Comment by marian42** [comment]
I agree. It works like that for preheating. I'm about to implement bed cooldown, currently it only cools tool0.

**Comment by olehs** [comment]
@mark-hahn Well, I know what you mean. Sometimes I also need to cool down only nozzle. But there still is separate button for this on OctoPrint's Temperature tab.
I think it would be great if there was a button with combobox instead of Preheat/Cooldown button in this plugin

**Comment by mark-hahn** [comment]
You mentioned tool0.  If my file uses only tool1 will everything work right?

**Comment by marian42** [comment]
@mark-hahn Preheating should work in that case. I haven't tested that though, since I have only one nozzle. Cooldown would not work in that case, but I'm working on a fix.
