### ISSUE TITLE
Preheat button enabled while disconnected

### ISSUE THREAD

**Issue by brdrck** [marian42/octoprint-preheat#15]
The preheat button is enabled while the rest of the buttons are disabled when the printer is disconnected:  ![image](https://user-images.githubusercontent.com/852684/37626581-033b5596-2ba7-11e8-8961-1a5c62877f1e.png)

When clicking the button it throws an error: 
![image](https://user-images.githubusercontent.com/852684/37626641-3948be26-2ba7-11e8-9093-01c8094901dc.png)

**Comment by marian42** [comment]
Fixed in 65d0a31c533131c5716fbddeed38f642fd1860b4
