### ISSUE TITLE
Feature request : notification

### ISSUE THREAD

**Issue by alexisju** [marian42/octoprint-preheat#16]
It could be a nice improvement of this (great) plugin to add a notification (visual /   sound) when the printer and the bed achieve the good temp.

**Comment by adrianmihalko** [comment]
Another feature request: preheat bed too.

**Comment by marian42** [comment]
@adrianmihalko Bed preheating is already implemented.

**Comment by adrianmihalko** [comment]
Super, I wanted to ask, because I haven't see any reference to it. I am in the center of a print, but I will install this plugin asap.

**Comment by marian42** [comment]
Sorry, the notification feature will not be added.

**Comment by alexisju** [comment]
Thank you.

**Comment by marian42** [comment]
I just pushed an update that adds this feature.
