### ISSUE TITLE
doesn’t seem to support multiple heads

### ISSUE THREAD

**Issue by autonumous** [marian42/octoprint-preheat#19]
only seems to preheat hot end 0, when the print only uses hot end 1

**Comment by Stady234** [comment]
If firmware is Marlin... the command that is sent is M104 (http://marlinfw.org/docs/gcode/M104.html)

it looks like it just needs slight mod to say = 
                         Set target temperature for E1
                         M104 T1 S205
                         M104 T0 S205

------------------
But this is also based on a split dual head... my cyclops uses on heater and one nozzle with the y splitter in the cold end.

**Comment by marian42** [comment]
@autonumous Preheating multiple hotends should be supported. Can you post a gcode file where it doesn't work?

**Comment by autonumous** [comment]
@marian42  Taking a cursory look at the code, i agree.  

Anyway I’ve updated  to v0.3 and tried the preheat, it functioned as expected.

I’ll try to locate the original g-code file and test again.

Maybe i just had too much new year ‘Fizz’ ...

**Comment by theamazingfedex** [comment]
I am also experiencing an issue with it not preheating the correct hotend, always defaults to preheating Tool-0. I have included a pastebin with the first chunk of gcode from a file in which this occurs, though it occurs for every file I attempt.
https://pastebin.com/2EsAMCDX

**Comment by marian42** [comment]
In line 24 of the gcode file, the temperature is missing:

    M104 S[extruder1_temperature] T1 ; Heat left extruder

From a quick google search, it looks like this is the result of a configuration error in Simplify3D. If I replace `[extruder1_temeperature]` with a number, preheating works as expected. The gcode files has some more placeholders. @theamazingfedex

**Comment by theamazingfedex** [comment]
Hmm, I haven't seen a setting in s3d to configure the pre-heat temperature. I just figured the plugin was using the same temp as the first layer.

**Comment by marian42** [comment]
Yes, this is not preheat-specific. The gcode file you provided is not a valid gcode file. I assume that the lines with the missing numbers are just ignored when printing. In the excerpt you posted there is no `M04` or `M09` command that sets the temperature for tool 1.

**Comment by theamazingfedex** [comment]
Ah, this isn't an issue with s3d's gcode, as the provided gcode was generated with cura. I've been having issues with getting cura to generate code properly, and at this point am on the verge of giving up on it entirely.

**Comment by marian42** [comment]
I'm going to close the issue as the problem seems to be unrelated to the preheat plugin. If there is a problem with the plugin, let me know and I'll reopen.
