### ISSUE TITLE
index() raises an exception if no pattern (";") was found.

### ISSUE THREAD

**Issue by olehs** [marian42/octoprint-preheat#2]
https://github.com/marian42/octoprint-preheat/blob/1eaac5bba96a4236979ad60e03fbef3918ead741/octoprint_preheat/__init__.py#L48

Please, use [find()](https://docs.python.org/2/library/string.html) instead

**Comment by olehs** [comment]
Thanks. But now it also cannot parse commands like
M104 S230 T0

This is from Simplify3D. Should I open a new issue?

**Comment by marian42** [comment]
I'll look into that. You don't need to open an issue.
