### ISSUE TITLE
send gcode before preheating

### ISSUE THREAD

**Issue by seltix5** [marian42/octoprint-preheat#27]
hello,

because I use PSU control the printer will not automaticly start alone.
sending a gcode like "M104" or other iteration wold be great :D

**Comment by marian42** [comment]
Currently, it already sends a M104 to perform the preheating. I don't quite understand the question.

**Comment by seltix5** [comment]
hello,
i dont know why but before it did not work :S but now it's working as expected.
sorry for the ticket, maybe something I changed in the settings :O
