### ISSUE TITLE
Add fan settings for preheating

### ISSUE THREAD

**Issue by ZhenyaKa** [marian42/octoprint-preheat#32]
When preheating with no fan on fan duct heating very strong and deforming.

Pls add option for fan speed settings when preheating is on!

**Comment by marian42** [comment]
I just added an option to run custom gcode when the Preheat button is pressed before the temeperatures are set. You could add a command there to set the fan speed. Let me know if this solves the problem or if you need something else.

**Comment by ZhenyaKa** [comment]
> I just added an option to run custom gcode when the Preheat button is pressed before the temeperatures are set. You could add a command there to set the fan speed. Let me know if this solves the problem or if you need something else.

Yes it's great solution.
It fine to add the same options when printing end and power on fan while temp go down to 30-40C for example, but I think your good addon can't solve that problem :(
