### ISSUE TITLE
Wrong Hotend #0 preheated instead of #1

### ISSUE THREAD

**Issue by sameSEA** [marian42/octoprint-preheat#33]
Hotend 0 being preheated instead of 1. The starting gcode:

`;FLAVOR:Marlin`
`;TIME:4780`
`;Filament used: 0m, 7.18108m`
`;Layer height: 0.25`
`;MINX:31.2`
`;MINY:90.9`
`;MINZ:0.3`
`;MAXX:151.471`
`;MAXY:195.8`
`;MAXZ:24.3`
`;Generated with Cura_SteamEngine 4.5.0`
`T1`
`M140 S80`
`M105`
`M190 S80`
`M104 S235`
`M105`
`M109 S235`
`M82 ;absolute extrusion mode`
`G21 ;metric values`
`G90 ;absolute positioning`
`M82 ;set extruder to absolute mode`
`M280 P0 S15 ; Switch to 1st extruder`
`M107 ;start with the fan off`
`G28 X0 Y0 ;move X/Y to min endstops`
`G28 Z0 ;move Z to min endstops`
`G1 Z15.0 F9000 ;move the platform down 15mm`
`G92 E0 ;zero the extruded length`
`G1 F200 E3 ;extrude 3mm of feed stock`
`G92 E0 ;zero the extruded length again`
`G1 F9000`
`M117 Printing...`
`G92 E0`

**Comment by marian42** [comment]
Thank you, I didn't know about the `T1` command, but I just added support for that command and now the example script is handled correctly.
