### ISSUE TITLE
Icon issues with plugin (plus easy request)

### ISSUE THREAD

**Issue by MattariOnline** [marian42/octoprint-preheat#35]
Hey, so I just wanted to report that I noticed an issue where with the plugin installed, the icons for the button didn't work. Additionally, if I remember correctly (as I modified it to remove the icons that were breaking), I think it was also messing up the other icons? This was on the latest version of octoprint as of the latest release of the plugin.

Also, I'd like to add a super easy suggestion:
_Could you consider adding a toggle that forces the fallback temperatures even if a file is loaded?_
I hate pre-heating the model's print heat early and getting extra extruding, wasted filament, rather than being able to set my fallback to under the melting point. This way I can warm it up, shorten the time to begin printing that first layer, without a ton of waste.

**Comment by marian42** [comment]
Can you share a screenshot of the missing icons? Which other plugins are you using?
