### ISSUE TITLE
Using Preheat button, target temp display 0°C while offset and actual tool temp are as expected

### ISSUE THREAD

**Issue by Chrominator** [marian42/octoprint-preheat#38]
OctoPrint: 1.4.0 running on a raspberry pi 3 with Raspbian GNU/Linux 9.11 (stretch)

Minor bug I think, does not impact the printings.
At start, when changing the tool temperature with an offset, it is taken into account in the actual tool temperature in OctoPrint and on the printer, however the Target temperature remains to 0.

Operations :

1- Power up the printer (via OctoPrint menu and an API call to Domoticz platform).
2- Refresh available serial ports.
3- Click on Connect button. Connexion made with the printer.
4- Change tool offset temperature +10¨C.
![Screenshot_2020-05-04 OctoPrint](https://user-images.githubusercontent.com/16359046/80985554-ac16bd80-8e2f-11ea-8a27-94d3a2c97f65.png)

Result as the following : 
![Screenshot_2020-05-04 OctoPrint(1)](https://user-images.githubusercontent.com/16359046/80985720-df594c80-8e2f-11ea-931b-e30109ec3935.png)

5- Load gcode file with the "Load" button.
![Screenshot_2020-05-04 OctoPrint(2)](https://user-images.githubusercontent.com/16359046/80986304-ad94b580-8e30-11ea-9228-82e911ba541e.png)

Status is Ok : 
![Screenshot_2020-05-04 OctoPrint(6)](https://user-images.githubusercontent.com/16359046/80987313-2ba58c00-8e32-11ea-976d-75403384ce9a.png)

6- Click "Preheat" buttons
Target tool temperature remains 0.
![image](https://user-images.githubusercontent.com/16359046/80987488-690a1980-8e32-11ea-8d36-e9fc1422c7ed.png)

When the bed and the tool are at the target temperature, the target tool still show 0°C.

![image](https://user-images.githubusercontent.com/16359046/80987692-b4242c80-8e32-11ea-8dde-86c6ca8045b1.png)

Please note that the same operations except clicking on the "Print" button at stage 5 which starts the heating does display the right target tool temperature.

**Comment by marian42** [comment]
I can reproduce this issue, however, it's a problem with Octoprint. I get the same bug with no plugin installed if I select an offset (Target changes from "off" to "0"), go to another tab and change the target temperature. The "0" will stay and not show the correct value.
