### ISSUE TITLE
Cannot get wide Print button with Pause, Cancel, Preheat underneath.

### ISSUE THREAD

**Issue by evannadeau** [marian42/octoprint-preheat#42]
I've used this plugin on several different versions of OctoPrint, but I have never gotten the button layout as in your screenshots.  It appears to put them all side by side, and the preheat button gets bumped down to a second row.  I do also use the Themify plugin, and I have tried with it turned off, and also tried adjusting the width of that sidebar to see if I could get the buttons to align better.

Is this an issue with the plugin, that should be adjusting that layout?  Or is there a method of performing the button adjustments that you could document, please?

Thanks.

**Comment by marian42** [comment]
My plugin does change the button layout. The way it works is a bit hacky, I would be surprised if it works with other theming plugins. But I've added support for one other theming plugin, so I can take a look at Themify. However, with no theming plugins installed, it should make the Print button wider like you say. Do you have any other plugins installed? Can you send a screenshot of the broken layout?
