### ISSUE TITLE
Receive popup that preheat cancelled, but it is actually continuing.

### ISSUE THREAD

**Issue by evannadeau** [marian42/octoprint-preheat#43]
Hello, I appear to have spotted a bug.  I am on Octoprint 1.5.2, and have several times spotted a popup stating preheat cancelled due to being manually changed, yet it continues. I had (now disabled for testing) the sequential heating enabled, and this message I believe appears right when the nozzle preheat kicks in.  I'll post if I find any more info.

![image](https://user-images.githubusercontent.com/1878498/102692049-1d905a00-41ce-11eb-8741-17cc5873450b.png)

**Comment by evannadeau** [comment]
Update: I just started another print, and I received the message immediately.  This is with the sequential heatup disabled, I'll try my next print with it on.  My suspicion is this message comes up when the nozzle heat starts.

**Comment by marian42** [comment]
This message should appear if you change the temperature menually while it preheats. I assume you didn't do that. If the message appears immediately, that's a bug. Does it happen all the time or only sometimes? Do you have any options in the plugin that aren't the default? Do you have any other Octoprint plugins installed?
