### ISSUE TITLE
Python 3 incompatibility

### ISSUE THREAD

**Issue by feuerwasser85** [marian42/octoprint-preheat#45]
Hi, love your Plugin. Could you make it python 3 compatible? THX!

**Comment by marian42** [comment]
I added support for Python 3 in 62627b852b8773e8c9be577cca39fd2fbd6ff92c, it should work. Do you have any problems running this Plugin with Python 3?

**Comment by cp2004** [comment]
Works for me just fine on Python 3, been using this for years (not on Py3, but you get the idea)
