### ISSUE TITLE
Preheat button grey out

### ISSUE THREAD

**Issue by eltonooi** [marian42/octoprint-preheat#48]
![image](https://user-images.githubusercontent.com/71483123/108295867-703cc100-71d3-11eb-9513-7619582ef7e9.png)

**Comment by eltonooi** [comment]
![image](https://user-images.githubusercontent.com/71483123/108295922-8ea2bc80-71d3-11eb-8f00-0ac65884363c.png)
when manually set the temperature high, the cool button is working. this is ender 3 v2 with smith3D BLtouch firmware (E3V2-2.0. x-16-3)

**Comment by cp2004** [comment]
You have to select a file for it to know what to preheat to.

**Comment by eltonooi** [comment]
> You have to select a file for it to know what to preheat to.

Got it, Thank you so much !
