### ISSUE TITLE
 Preheating failed. Could not find any preheat commands in the gcode file.

### ISSUE THREAD

**Issue by sourekv** [marian42/octoprint-preheat#61]
Hello,
for my file

[bolt_0.2mm_PETG_MK3S_1h49m.gcode.zip](https://github.com/marian42/octoprint-preheat/files/12451711/bolt_0.2mm_PETG_MK3S_1h49m.gcode.zip)

I have encountered following error:

```
Preheating failed.
Could not find any preheat commands in the gcode file. You can configure fallback temperatures for this case.
```

Could you please investigate the issue?

If there is something I can do. Let me know.
Thanks a lot.

Vlada

[octoprint-systeminfo-20230828095106.zip](https://github.com/marian42/octoprint-preheat/files/12451733/octoprint-systeminfo-20230828095106.zip)

**Comment by KnobFaces** [comment]
In that GCode the heatup commands appear around line 1120 due to an embedded thumbnail. The default read is 1000 lines.

**Comment by sourekv** [comment]
Thanks for explanation. Since then I have stopped using a plugin. I guess that fix is a feature request. Should I close this issue?

**Comment by KnobFaces** [comment]
You can specify the number of lines to process in the options.

**Comment by sourekv** [comment]
Great, Thanks
