### ISSUE TITLE
Request: disable nozzle preheat

### ISSUE THREAD

**Issue by TylonHH** [marian42/octoprint-preheat#7]
Hi,
I'd like to choose bymyself weather I want to preheat both (nozzle and bed) oder just one of them.
In my case I just wanna preheat my bed.
Cheers

**Comment by marian42** [comment]
Should the cooldown button be affected by this setting or should it always cool down both the tool and nozzle?

**Comment by TylonHH** [comment]
Good questing for discussion.
I think "cool all down" makes the most sense.
