### ISSUE TITLE
Messed up state wrapper

### ISSUE THREAD

**Issue by n8name** [marian42/octoprint-preheat#8]
Plugin messes up div state_wrapper. OctoPrint Version 1.3.5
<img width="316" alt="display error" src="https://user-images.githubusercontent.com/3366874/33455442-6598155c-d61c-11e7-8959-93dabbfc3aab.png">

**Comment by marian42** [comment]
Are you using TouchUI?

**Comment by n8name** [comment]
Yes, I do. Is there a known conflict between these two plugins?

**Comment by marian42** [comment]
No, this is my attempt to make my plugin compatible with TouchUI. Are you using a theme? When I installed TouchUI I got a dark flat design. I added some css rules to work with that design and these rules mess up the view in your screenshot.

**Comment by n8name** [comment]
Both OctoPrint and TouchUI themes are the default ones. Can you provide a workaround? 
Honestly I have not used TouchUI that often simply because I use the Telegram Plugin.

**Comment by marian42** [comment]
I would like to know how to reproduce your problem so I can fix it. When I installed TouchUI, it looked like the screenshots [here](http://plugins.octoprint.org/plugins/touchui/), not like the screenshot you provided. Is it possible you have TouchUI installed but disabled?

Uninstalling TouchUI would be a workaround.

**Comment by marian42** [comment]
Nevermind, I just realized you can have TouchUI installed but still use the default layout. I'll fix this later today.
