### ISSUE TITLE
"No preheat command in file" on every print from Cura

### ISSUE THREAD

**Issue by Stady234** [marian42/octoprint-preheat#9]
Every time i send new job to octoprint from cura 3.0.4, the plugin button when clicked states that there is no preheat command found.

**Comment by NeoTrace82** [comment]
I do have the same issue and wanted to create an issue, ill upload a gcode file from a current CURA 3.0.4 Installation in a second

**Comment by NeoTrace82** [comment]
[AA_DMG_v1.1.zip](https://github.com/marian42/octoprint-preheat/files/1520783/AA_DMG_v1.1.zip)

**Comment by marian42** [comment]
I just tested the file and it works as expected for me. Can you confirm that the error still appears after removing and reinstalling the plugin?

**Comment by Stady234** [comment]
After re-install, everything is working as it should.  Not sure why it acted like that...

**Comment by NeoTrace82** [comment]
Same for me did reinstall, now it works
